function draw = getEmptyDrawStruct()
    draw = struct('logPosterior',[], ...
    'ps', [], ...
    'qs', [], ...
    'sigmaEs', [],...
    'arParameters',     [],...
    'maParameters',     [],...
    'arPacs',           [],...
    'maPacs',           [],...
    'accepted',         [],...
    'drawDropped',      [],...
    'logProposal',      [],...
    'estimatedVariance', [],...
    'alpha', []);
end